# Domain –Retail

focus –Optimize Book RENT


Business challenge/requirement


BookRent is the largest online and offline book rental chain in India. 

TheCompany charges a fixed fee per month plus rental per book. 
So,the company makes more money when user rent more books. 

You as an ML expert have to model recommendation engine so that user gets recommendation of books based on the behaviorof similar users. 

This will ensure that users are renting books based on their individual taste.
Company is still unprofitable and is looking to improve both revenue and profit.

# Data volume-Approx 


1 M  records –file BX-Book-Ratings.csv and 2 more. But only 10K records will be usedFields in Data

•user_id: Unique Id of the User
    
•isbn: International Standard Book Number is a unique numeric commercial book identifier
    
•rating: rating given by userAdditional information-NA


In [1]:
import pandas as pd
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
#Reading users file:
#u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv('BX-Users.csv',encoding='latin-1')

D:\Users\Plaban_Nayak\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
users.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [62]:
#Reading ratings file:
#r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1')
ratings.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [63]:
ratings.shape

(1048575, 3)

In [64]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
user_id    1048575 non-null int64
isbn       1048575 non-null object
rating     1048575 non-null int64
dtypes: int64(2), object(1)
memory usage: 24.0+ MB


In [65]:
labels = LabelEncoder()
items_isbn = labels.fit_transform(ratings['isbn'])
ratings['items'] = items_isbn

In [66]:
labels = LabelEncoder()
items = labels.fit_transform(ratings['user_id'])
ratings['user'] = items

In [67]:
ratings.head()

user_id        isbn  rating   items   user
0   276725  034545104X       0    4511  94663
1   276726   155061224       5   30815  94664
2   276727   446520802       0  158458  94665
3   276729  052165615X       3    9704  94666
4   276729   521795028       6  177084  94666

In [68]:
ratings = ratings.sort_values(['user','items'])

In [69]:
ratings.head()

user_id        isbn  rating   items  user
9561        2   195153448       0   62661     0
9562        7    34542252       0  103304     1
9571        8  074322678X       5   14124     2
9574        8  080652121X       0   15936     2
9576        8  1552041778       5   31945     2

In [70]:
sample_ratings = ratings[['user','items','rating']].head(10000)

In [71]:
sample_ratings.shape

(10000, 3)

In [72]:
sample_ratings.head()

user   items  rating
9561     0   62661       0
9562     1  103304       0
9571     2   14124       5
9574     2   15936       0
9576     2   31945       5

In [77]:
counts = sample_ratings['items'].nunique()

In [78]:
unique = sample_ratings['items'].unique()

In [81]:
en = {}
for i in range(len(unique)):
    en[unique[i]] = i

In [83]:
sample_ratings['items_en'] = sample_ratings['items'].map(en)

In [84]:
sample_ratings.head()

user   items  rating  items_en
9561     0   62661       0         0
9562     1  103304       0         1
9571     2   14124       5         2
9574     2   15936       0         3
9576     2   31945       5         4

In [85]:
final_ratings = sample_ratings[['user','items_en','rating']]

In [86]:
final_ratings.shape

(10000, 3)

In [87]:
final_ratings.head()

user  items_en  rating
9561     0         0       0
9562     1         1       0
9571     2         2       5
9574     2         3       0
9576     2         4       5

In [46]:
#Reading items file:
items = pd.read_csv('BX-Books.csv',encoding='latin-1')
items.head()

D:\Users\Plaban_Nayak\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

#### Users

In [14]:
users.isnull().sum()

user_id          0
Location         1
Age         110763
dtype: int64

In [15]:
users.Age.fillna('0',inplace=True)

In [16]:
print(users.shape)

users.head()

(278859, 3)


user_id                            Location Age
0       1                  nyc, new york, usa   0
1       2           stockton, california, usa  18
2       3     moscow, yukon territory, russia   0
3       4           porto, v.n.gaia, portugal  17
4       5  farnborough, hants, united kingdom   0

In [17]:

users = users.head(10000)
print(users.shape)

(10000, 3)


In [18]:
users.head()

user_id                            Location Age
0       1                  nyc, new york, usa   0
1       2           stockton, california, usa  18
2       3     moscow, yukon territory, russia   0
3       4           porto, v.n.gaia, portugal  17
4       5  farnborough, hants, united kingdom   0

#### Ratings

In [19]:
print(sample_ratings.shape)
sample_ratings.head()

(10000, 3)


user_id  items  rating
371995    89192      0       0
278225    65520      1       0
826759   199864      2       5
800326   194500      3       0
512107   124304      4       8

#### Items

In [20]:
print(items.shape)
items.head()

(271379, 5)


isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [21]:
items = items.head(10000)
print(items.shape)
items.head()

(10000, 5)


isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [22]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048575 entries, 371995 to 353525
Data columns (total 4 columns):
user_id    1048575 non-null int64
isbn       1048575 non-null object
rating     1048575 non-null int64
items      1048575 non-null int64
dtypes: int64(3), object(1)
memory usage: 40.0+ MB


In [23]:
"""import re
count = 0
def replace_char(x):
    s = re.sub('[0/$.+a-zA-Z]+', '', x)
    #print(s)
    if s == '':
        s = 0
    return np.abs(int(s))
"""

"import re\ncount = 0\ndef replace_char(x):\n    s = re.sub('[0/$.+a-zA-Z]+', '', x)\n    #print(s)\n    if s == '':\n        s = 0\n    return np.abs(int(s))\n"

In [ ]:
sample_rat

In [103]:
from sklearn.model_selection import train_test_split
ratings_train,ratings_test = train_test_split(final_ratings,test_size=0.25,random_state=1)

In [104]:
ratings_train.shape, ratings_test.shape

((7500, 3), (2500, 3))

In [106]:
ratings_train.head()

user  items_en  rating
10195    95       637       0
16121   943      5949       8
18409  1177      1954       0
11880   303      2245       9
15207   791      5187       7

In [107]:
ratings_test.head()

user  items_en  rating
19513  1312       659       8
13399   600      3561       8
14509   732      4556       0
13440   600      3592       7
14975   791      4983       0

#### Building collaborative filtering model from scratch

We will recommend movies based on user-user similarity and item-item similarity. For that, first we need to calculate the number of unique users and movies.

In [88]:
final_ratings.columns

Index(['user', 'items_en', 'rating'], dtype='object')

In [50]:
sample_ratings['items'].unique()

array([ 62661, 103304,  14124, ..., 202818, 243733,  84274], dtype=int64)

In [89]:
n_users = final_ratings['user'].nunique()
n_items = final_ratings['items_en'].nunique()

print(n_users)
print(n_items)

1323
8742


In [90]:
final_ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 9561 to 19560
Data columns (total 3 columns):
user        10000 non-null int64
items_en    10000 non-null int64
rating      10000 non-null int64
dtypes: int64(3)
memory usage: 312.5 KB


#### create a user-item matrix which can be used to calculate the similarity between users and items.

In [91]:
data_matrix = np.zeros((n_users, n_items))

In [92]:
data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [93]:
data_matrix.shape

(1323, 8742)

In [96]:
for line in final_ratings.itertuples():
    #print(line[1], line[2],line[3])
    data_matrix[line[1], line[2]] = line[3]

In [98]:
data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 5., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### we will calculate the similarity. 

We can use the pairwise_distance function from sklearn to calculate the cosine similarity.

In [99]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(data_matrix,metric='cosine')
items_similarity = pairwise_distances(data_matrix.T,metric='cosine')

This gives us the item-item and user-user similarity in an array form

In [100]:
user_similarity.shape,items_similarity.shape

((1323, 1323), (8742, 8742))

In [101]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

we will make predictions based on user similarity and item similarity.

In [109]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, items_similarity, type='item')

In [110]:
user_prediction

array([[-0.00305306, -0.00305306,  0.00072909, ..., -0.00305306,
        -0.00305306, -0.00305306],
       [-0.00305306, -0.00305306,  0.00072909, ..., -0.00305306,
        -0.00305306, -0.00305306],
       [ 0.00141153,  0.00141153,  0.00141153, ...,  0.00141153,
         0.00141153,  0.00141153],
       ...,
       [ 0.01114207,  0.01114207,  0.01492421, ...,  0.01114207,
         0.01114207,  0.01114207],
       [-0.00042009, -0.00042009,  0.00336205, ..., -0.00042009,
        -0.00042009, -0.00042009],
       [-0.00305306, -0.00305306,  0.00072909, ..., -0.00305306,
        -0.00305306, -0.00305306]])

In [114]:
train_data_matrix = np.zeros((n_users, n_items))
test_data_matrix =  np.zeros((n_users, n_items))

In [115]:
for line in ratings_train.itertuples():
    train_data_matrix[line[1], line[2]] = line[3]
    
for line in ratings_test.itertuples():
    test_data_matrix[line[1], line[2]] = line[3]

In [116]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 5., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [117]:
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [122]:
from sklearn.metrics import mean_squared_error
def rmse(pred,test):
    pred = pred[test.nonzero()].flatten()
    test = test[test.nonzero()].flatten()
    return np.sqrt(mean_squared_error(pred,test))

#### Root Mean Squared error for user predictions on test data matrix

In [123]:
rmse(user_prediction,test_data_matrix)

7.893022392190806

#### Root Mean Squared error on items prediction on test data matrix

In [124]:
rmse(item_prediction,test_data_matrix)

7.925652403554382