<a href="https://colab.research.google.com/github/plaban1981/recommendation-engine/blob/master/KNN_Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Movie Recommendation  Engine using K Nearest Neighbor

source :https://towardsdatascience.com/

## Dataset url: https://grouplens.org/datasets/movielens/latest/

https://medium.com/@zhang_yang/number-of-parameters-in-dense-and-convolutional-neural-networks-34b54c2ec349

## Import movies data

In [21]:
from google.colab import files
files.upload()

Saving movies.csv to movies.csv


{'movies.csv': b'movieId,title,genres\r\n1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy\r\n2,Jumanji (1995),Adventure|Children|Fantasy\r\n3,Grumpier Old Men (1995),Comedy|Romance\r\n4,Waiting to Exhale (1995),Comedy|Drama|Romance\r\n5,Father of the Bride Part II (1995),Comedy\r\n6,Heat (1995),Action|Crime|Thriller\r\n7,Sabrina (1995),Comedy|Romance\r\n8,Tom and Huck (1995),Adventure|Children\r\n9,Sudden Death (1995),Action\r\n10,GoldenEye (1995),Action|Adventure|Thriller\r\n11,"American President, The (1995)",Comedy|Drama|Romance\r\n12,Dracula: Dead and Loving It (1995),Comedy|Horror\r\n13,Balto (1995),Adventure|Animation|Children\r\n14,Nixon (1995),Drama\r\n15,Cutthroat Island (1995),Action|Adventure|Romance\r\n16,Casino (1995),Crime|Drama\r\n17,Sense and Sensibility (1995),Drama|Romance\r\n18,Four Rooms (1995),Comedy\r\n19,Ace Ventura: When Nature Calls (1995),Comedy\r\n20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller\r\n21,Get Shorty (1995),Comedy|Crime|Thril

In [0]:
import numpy as np
import pandas as pd

## Load data into pandas dataframe

In [0]:
movies_df = pd.read_csv('movies.csv',usecols=['movieId','title'],dtype={'movieId': 'int32', 'title': 'str'})
rating_df=pd.read_csv('ratings.csv',usecols=['userId', 'movieId', 'rating'],dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32'})

In [32]:
movies_df.head()

movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [33]:
rating_df.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

## merge the movies and ratings data

In [34]:
df = pd.merge(movies_df,rating_df,on='movieId')
df.head()

movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

## Check for null values

In [35]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

## drop null values if any present in title column

In [30]:
combine_movie_rating = df.dropna(subset=['title'],axis = 0)
combine_movie_rating.head()

movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

## Count of ratings per movie

In [36]:
movie_ratingCount = combine_movie_rating.groupby('title')['rating'].count().reset_index().rename(columns = {'rating': 'totalRatingCount'})[['title', 'totalRatingCount']]
    
movie_ratingCount.head()

title  totalRatingCount
0                               '71 (2014)                 1
1  'Hellboy': The Seeds of Creation (2004)                 1
2                   'Round Midnight (1986)                 2
3                      'Salem's Lot (2004)                 1
4                'Til There Was You (1997)                 2

## Retrieve totalRatingCount into training data with ovie and ratings

In [37]:
rating_with_totalRatingCount = pd.merge(combine_movie_rating,movie_ratingCount,on = 'title', how = 'left')
rating_with_totalRatingCount.head()

movieId             title  userId  rating  totalRatingCount
0        1  Toy Story (1995)       1     4.0               215
1        1  Toy Story (1995)       5     4.0               215
2        1  Toy Story (1995)       7     4.5               215
3        1  Toy Story (1995)      15     2.5               215
4        1  Toy Story (1995)      17     4.5               215

## Statistics of the totalRatingCount

In [38]:
print(movie_ratingCount['totalRatingCount'].describe())

count    9719.000000
mean       10.375141
std        22.406220
min         1.000000
25%         1.000000
50%         3.000000
75%         9.000000
max       329.000000
Name: totalRatingCount, dtype: float64


## Defining a threshold and taking into consideration those movies which have been rated greater than the threshold times

In [39]:
popularity_threshold = 50
rating_popular_movie= rating_with_totalRatingCount[rating_with_totalRatingCount.totalRatingCount >= popularity_threshold]
rating_popular_movie.head()

movieId             title  userId  rating  totalRatingCount
0        1  Toy Story (1995)       1     4.0               215
1        1  Toy Story (1995)       5     4.0               215
2        1  Toy Story (1995)       7     4.5               215
3        1  Toy Story (1995)      15     2.5               215
4        1  Toy Story (1995)      17     4.5               215

In [40]:
rating_popular_movie.shape

(41362, 5)

## Create a user - movie rating matrix

In [0]:
movie_features_df=rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)

In [42]:
movie_features_df.head()

userId                             1    2    3    4    ...  607  608  609  610
title                                                  ...                    
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
12 Angry Men (1957)                0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0  0.0
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  ...  0.0  3.0  0.0  4.5
28 Days Later (2002)               0.0  0.0  0.0  0.0  ...  0.0  3.5  0.0  5.0
300 (2007)                         0.0  0.0  0.0  0.0  ...  0.0  5.0  0.0  4.0

[5 rows x 606 columns]

In [0]:
from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(movie_features_df.values)

In [44]:
type(movie_features_df_matrix)

scipy.sparse.csr.csr_matrix

In [46]:
movie_features_df_matrix.shape

(450, 606)

In [47]:
movie_features_df_matrix[0]

<1x606 sparse matrix of type '<class 'numpy.float32'>'
	with 54 stored elements in Compressed Sparse Row format>

In [49]:
movie_features_df.head()

userId                             1    2    3    4    ...  607  608  609  610
title                                                  ...                    
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
12 Angry Men (1957)                0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0  0.0
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  ...  0.0  3.0  0.0  4.5
28 Days Later (2002)               0.0  0.0  0.0  0.0  ...  0.0  3.5  0.0  5.0
300 (2007)                         0.0  0.0  0.0  0.0  ...  0.0  5.0  0.0  4.0

[5 rows x 606 columns]

## Build the model

In [48]:
from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

## Recommending Movies Based on trained Model

In [56]:
query_index = np.random.choice(movie_features_df.shape[0])
print(query_index)
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 6)

433


In [53]:
movie_features_df.iloc[query_index,:].values.reshape(1, -1)

array([[0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 3.5, 0. , 4.5,
        0. , 1.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3. , 0. , 2.5, 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 3. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. 

In [51]:
distances

array([[0.        , 0.47542155, 0.52756166, 0.54977226, 0.5511641 ,
        0.5720538 ]], dtype=float32)

In [54]:
indices.flatten()

array([140, 335, 322, 334,  50,  35])

In [57]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(movie_features_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, movie_features_df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Wedding Singer, The (1998):

1: Grease (1978), with distance of 0.48272883892059326:
2: Grosse Pointe Blank (1997), with distance of 0.5014654397964478:
3: Goonies, The (1985), with distance of 0.5163264274597168:
4: Austin Powers: International Man of Mystery (1997), with distance of 0.5165428519248962:
5: Christmas Story, A (1983), with distance of 0.5204477310180664:
